GET http://localhost:8080/jakartaee-poc/api/agregadores/
###

GET http://localhost:8080/jakartaee-poc/api/agregadores/{id}
###

POST http://localhost:8080/jakartaee-poc/api/agregadores/
###

POST http://localhost:8080/jakartaee-poc/api/agregadores/{id}/entidades/

entidade
###

POST http://localhost:8080/jakartaee-poc/api/agregadores/{id}/objetos/

objeto
###

DELETE http://localhost:8080/jakartaee-poc/api/agregadores/{id}
###
